version: '3.3'
services:
  webapp:
    restart: always
    image: "carrefour.app"              #第一种模式，直接读取镜像
    #container_name: "carrefourapp"     #第二种模式，自己构造镜像
    #build:
      #context: .
      #dockerfile: Dockerfile
    ports:
      - "8085:80"
    links:
      - rabbitmq
    volumes: 
      #- "./log:/gary/carrefour/log"
      - "./appsettings.json:/gary/carrefour"
  rabbitmq:
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_VHOST: "/Carrefour_Virtual_host"
      RABBITMQ_DEFAULT_USER: "carrefour"
      RABBITMQ_DEFAULT_PASS: "carrefour"
    image: "rabbitmq:3.7.16-management"
    restart: always
    volumes:
      - "./data:/var/lib/rabbitmq"
      - "./log:/var/log/rabbitmq/log"
    ports:
      - "15672:15672"
      - "4369:4369"
      - "5672:5672"
      - "25672:25672"